# Generated by Django 4.2.6 on 2024-06-04 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cid_localizacao_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrecaoBairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro_incorreto', models.CharField(max_length=100, unique=True)),
                ('bairro_correto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('relatorio', models.FileField(upload_to='relatorios')),
            ],
        ),
        migrations.CreateModel(
            name='Casos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(max_length=100)),
                ('cid', models.CharField(max_length=100)),
                ('descricao_cid', models.CharField(max_length=200)),
                ('quantidade_casos', models.IntegerField()),
                ('data', models.DateField()),
                ('relatorio', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Cid_localizacao_app.relatorio')),
            ],
        ),
    ]
